local_costmap:
  global_frame: odom # 局部坐标系（里程计，减少漂移）
  robot_base_frame: base_link
  update_frequency: 5.0 # 更新频率（5Hz，需高于全局）
  publish_frequency: 5.0
  static_map: false # 不使用静态地图（依赖激光实时更新）
  rolling_window: true # 滚动窗口（随机器人移动更新视野）
  width: 4.027 # 局部地图宽度（3米）
  height: 4.027 # 局部地图高度（3米）
  resolution: 0.05
  track_unknown_space: true # 跟踪未知空间（避免地图中空洞）
  transform_tolerance: 0.5
